Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-service
  AttributeDefinitions:
    -
      AttributeName: serviceId
      AttributeType: S
  KeySchema:
    -
      AttributeName: serviceId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.service.billingMode}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.service.provisionedThroughput.readCapacityUnits}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.service.provisionedThroughput.writeCapacityUnits}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

